# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookliketab',
            name='book_id',
            field=models.CharField(max_length=16),
        ),
    ]
