# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180602_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookliketab',
            name='book_desc',
        ),
        migrations.AddField(
            model_name='bookliketab',
            name='last_read_chapter_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookliketab',
            name='last_read_chapter_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookliketab',
            name='latest_chapter_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookliketab',
            name='book_img_url',
            field=models.CharField(max_length=256),
        ),
    ]
